name: Update CHANGELOG.md
on:
  issue_comment:
    types: [created]

  # For manually triggering this workflow
  workflow_dispatch:
    inputs:
      number:
        description: PR number
        required: true

jobs:
  update_changelog:
    runs-on: ubuntu-latest
    # Only run if comment is on a PR with the main repo, and if it contains the magic keywords
    if: >
      github.repository_owner == 'vladsavelyev'
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.MQC_BOT_GITHUB_TOKEN }}

      # Action runs on the issue comment, so we don't get the PR by default
      # Use the gh cli to check out the PR
      - name: Checkout Pull Request
        run: gh pr checkout ${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.MQC_BOT_GITHUB_TOKEN }}

      - uses: actions/setup-python@v4

      - name: Check if CHANGELOG.md was modified by other commits (including previous runs of this workflow)
        env:
          GH_TOKEN: ${{ secrets.MQC_BOT_GITHUB_TOKEN }}
        run: |
          pr_number=$(cat ./pr/pr_number)
          files=$(gh pr diff $pr_number --name-only)
          if [[ $files == *"CHANGELOG.md"* ]]; then
            echo "CHANGELOG.md was modified in this PR"
            echo "changelog_modified=true" >> $GITHUB_ENV
          else
            echo "CHANGELOG.md was not modified in this PR"
            echo "changelog_modified=false" >> $GITHUB_ENV
          fi

      - name: Update CHANGELOG.md from the PR title
        if: env.changelog_modified == 'false'
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          pr_number=$(cat ./pr/pr_number)
          python ${GITHUB_WORKSPACE}/.github/workflows/changelog.py

      - name: Check if CHANGELOG.md actually changed
        run: |
          git diff --exit-code ${GITHUB_WORKSPACE}/CHANGELOG.md || echo "changed=YES" >> $GITHUB_ENV
          echo "file changed: ${{ env.changed }}"

      - name: Push changes
        run: |
          git config user.name 'MultiQC Bot'
          git config user.email 'multiqc-bot@seqera.io'
          git config push.default upstream
          git add ${GITHUB_WORKSPACE}/CHANGELOG.md
          git status
          git commit -m "[automated] Update CHANGELOG.md"
          git push
