name: Update CHANGELOG.md

on:
  - pull_request
permissions: write-all
jobs:
  update_changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4

      - name: Check if CHANGELOG.md was modified by other commits (including previous runs of this workflow)
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          pr_number=${{ github.event.pull_request.number }}
          files=$(gh pr diff $pr_number --name-only)
          if [[ $files == *"CHANGELOG.md"* ]]; then
            echo "CHANGELOG.md was modified in this PR"
            echo "changelog_modified=true" >> $GITHUB_ENV
          else
            echo "CHANGELOG.md was not modified in this PR"
            echo "changelog_modified=false" >> $GITHUB_ENV
          fi

      - name: Update CHANGELOG.md from the PR title
        if: env.changelog_modified == 'false'
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: python ${GITHUB_WORKSPACE}/.github/workflows/changelog.py

      - name: Check if CHANGELOG.md actually changed
        run: |
          git diff --exit-code ${GITHUB_WORKSPACE}/CHANGELOG.md || echo "changed=YES" >> $GITHUB_ENV
          echo "file changed: ${{ env.changed }}"

      - name: Push changes
        if: env.changed == 'YES'
        id: push-local-repository-changes
        uses: reloc8/action-push-local-changes@1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit-message: "Update CHANGELOG.md"
