name: Trigger the changelog workflow
on:
  pull_request_review:
    branches:
      - master
    types:
      - submitted

jobs:
  trigger_changelog_workflow:
    runs-on: ubuntu-latest
    name: Trigger the changelog workflow
    steps:
      - name: Explanation
        run: echo "this is a dummy workflow that triggers a workflow_run; it's necessary because otherwise the repo secrets will not be in scope for externally forked pull requests"

